/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TouristRouteImport } from './routes/tourist'
import { Route as TouristIndexRouteImport } from './routes/tourist.index'
import { Route as TouristAiRouteImport } from './routes/tourist.ai'
import { Route as TouristExploreRouteImport } from './routes/tourist.explore'
import { Route as TouristProfileRouteImport } from './routes/tourist.profile'
import { Route as TouristRewardsRouteImport } from './routes/tourist.rewards'
import { Route as TouristExperienceIdRouteImport } from './routes/tourist.experience.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TouristRoute = TouristRouteImport.update({
  id: '/tourist',
  path: '/tourist',
  getParentRoute: () => rootRouteImport,
} as any)
const TouristIndexRoute = TouristIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TouristRoute,
} as any)
const TouristAiRoute = TouristAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => TouristRoute,
} as any)
const TouristExploreRoute = TouristExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => TouristRoute,
} as any)
const TouristProfileRoute = TouristProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TouristRoute,
} as any)
const TouristRewardsRoute = TouristRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => TouristRoute,
} as any)
const TouristExperienceIdRoute = TouristExperienceIdRouteImport.update({
  id: '/experience/$id',
  path: '/experience/$id',
  getParentRoute: () => TouristRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tourist': typeof TouristRouteWithChildren
  '/tourist/ai': typeof TouristAiRoute
  '/tourist/explore': typeof TouristExploreRoute
  '/tourist/profile': typeof TouristProfileRoute
  '/tourist/rewards': typeof TouristRewardsRoute
  '/tourist/': typeof TouristIndexRoute
  '/tourist/experience/$id': typeof TouristExperienceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tourist/ai': typeof TouristAiRoute
  '/tourist/explore': typeof TouristExploreRoute
  '/tourist/profile': typeof TouristProfileRoute
  '/tourist/rewards': typeof TouristRewardsRoute
  '/tourist': typeof TouristIndexRoute
  '/tourist/experience/$id': typeof TouristExperienceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tourist': typeof TouristRouteWithChildren
  '/tourist/ai': typeof TouristAiRoute
  '/tourist/explore': typeof TouristExploreRoute
  '/tourist/profile': typeof TouristProfileRoute
  '/tourist/rewards': typeof TouristRewardsRoute
  '/tourist/': typeof TouristIndexRoute
  '/tourist/experience/$id': typeof TouristExperienceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tourist'
    | '/tourist/ai'
    | '/tourist/explore'
    | '/tourist/profile'
    | '/tourist/rewards'
    | '/tourist/'
    | '/tourist/experience/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tourist/ai'
    | '/tourist/explore'
    | '/tourist/profile'
    | '/tourist/rewards'
    | '/tourist'
    | '/tourist/experience/$id'
  id:
    | '__root__'
    | '/'
    | '/tourist'
    | '/tourist/ai'
    | '/tourist/explore'
    | '/tourist/profile'
    | '/tourist/rewards'
    | '/tourist/'
    | '/tourist/experience/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TouristRoute: typeof TouristRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tourist': {
      id: '/tourist'
      path: '/tourist'
      fullPath: '/tourist'
      preLoaderRoute: typeof TouristRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tourist/': {
      id: '/tourist/'
      path: '/'
      fullPath: '/tourist/'
      preLoaderRoute: typeof TouristIndexRouteImport
      parentRoute: typeof TouristRoute
    }
    '/tourist/ai': {
      id: '/tourist/ai'
      path: '/ai'
      fullPath: '/tourist/ai'
      preLoaderRoute: typeof TouristAiRouteImport
      parentRoute: typeof TouristRoute
    }
    '/tourist/explore': {
      id: '/tourist/explore'
      path: '/explore'
      fullPath: '/tourist/explore'
      preLoaderRoute: typeof TouristExploreRouteImport
      parentRoute: typeof TouristRoute
    }
    '/tourist/profile': {
      id: '/tourist/profile'
      path: '/profile'
      fullPath: '/tourist/profile'
      preLoaderRoute: typeof TouristProfileRouteImport
      parentRoute: typeof TouristRoute
    }
    '/tourist/rewards': {
      id: '/tourist/rewards'
      path: '/rewards'
      fullPath: '/tourist/rewards'
      preLoaderRoute: typeof TouristRewardsRouteImport
      parentRoute: typeof TouristRoute
    }
    '/tourist/experience/$id': {
      id: '/tourist/experience/$id'
      path: '/experience/$id'
      fullPath: '/tourist/experience/$id'
      preLoaderRoute: typeof TouristExperienceIdRouteImport
      parentRoute: typeof TouristRoute
    }
  }
}

interface TouristRouteChildren {
  TouristAiRoute: typeof TouristAiRoute
  TouristExploreRoute: typeof TouristExploreRoute
  TouristProfileRoute: typeof TouristProfileRoute
  TouristRewardsRoute: typeof TouristRewardsRoute
  TouristIndexRoute: typeof TouristIndexRoute
  TouristExperienceIdRoute: typeof TouristExperienceIdRoute
}

const TouristRouteChildren: TouristRouteChildren = {
  TouristAiRoute: TouristAiRoute,
  TouristExploreRoute: TouristExploreRoute,
  TouristProfileRoute: TouristProfileRoute,
  TouristRewardsRoute: TouristRewardsRoute,
  TouristIndexRoute: TouristIndexRoute,
  TouristExperienceIdRoute: TouristExperienceIdRoute,
}

const TouristRouteWithChildren =
  TouristRoute._addFileChildren(TouristRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TouristRoute: TouristRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
